# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'week5.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
import re


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(632, 586)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(170, 40, 271, 22))
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(110, 40, 55, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(110, 70, 55, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(120, 100, 41, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(60, 130, 121, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(100, 170, 61, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(100, 350, 55, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(90, 400, 61, 16))
        self.label_7.setObjectName("label_7")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(170, 70, 271, 22))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(170, 100, 271, 22))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(170, 130, 271, 22))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(170, 170, 271, 161))
        self.textEdit.setObjectName("textEdit")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(170, 350, 131, 22))
        self.comboBox.setEditable(True)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.setItemText(0, "")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox_2 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_2.setGeometry(QtCore.QRect(170, 400, 131, 22))
        self.comboBox_2.setEditable(True)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.setItemText(0, "")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(170, 450, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(380, 450, 93, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(90, 500, 341, 16))
        self.label_8.setObjectName("label_8")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 632, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.pushButton.clicked.connect(self.save)
        self.pushButton_2.clicked.connect(self.clear)

        shortcut_quit = QtWidgets.QShortcut(QtGui.QKeySequence("Q"), MainWindow)
        shortcut_quit.setContext(
            QtCore.Qt.WidgetWithChildrenShortcut)
        shortcut_quit.activated.connect(MainWindow.close)

    def save(self):
        name = self.lineEdit.text().strip()
        email = self.lineEdit_2.text().strip()
        age = self.lineEdit_3.text().strip()
        phone = self.lineEdit_4.text().strip()
        address = self.textEdit.toPlainText().strip()
        gender = self.comboBox.currentText().strip()
        education = self.comboBox_2.currentText().strip()

        valid_genders = ["Male", "Female"]
        valid_educations = [
            "Elementary School", "Junior High School", "Senior High School",
            "Diploma", "Bachelor’s Degree", "Master’s Degree", "Doctoral Degree"
        ]

        if not name:
            self.show_error_message("Name is required!")
            return

        if not email or not re.match(r"[^@]+@[^@]+\.[^@]+", email):
            self.show_error_message("Please enter a valid email address!")
            return

        age = int(age)
        if age < 15 or age > 100:
            self.show_error_message("Age must be between 15 and 100!")
            return

        if not re.match(r"^\+62 \d{3} \d{4} \d{3,4}$", phone):
            self.show_error_message("Please enter a valid phone number!")
            return

        if gender not in valid_genders:
            self.show_error_message("Please select a valid gender!")
            return

        if education not in valid_educations:
            self.show_error_message("Please select a valid education level!")
            return

        QMessageBox.information(None, "Profile", "Profile has been saved!")

    def clear(self):
        self.lineEdit.clear()
        self.lineEdit_2.clear()
        self.lineEdit_3.clear()
        self.lineEdit_4.clear()
        self.textEdit.clear()
        self.comboBox.setCurrentIndex(0)
        self.comboBox_2.setCurrentIndex(0)

    def show_error_message(self, message):
        QMessageBox.critical(None, "Error", message)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Name:"))
        self.label_2.setText(_translate("MainWindow", "Email:"))
        self.label_3.setText(_translate("MainWindow", "Age:"))
        self.label_4.setText(_translate("MainWindow", "Phone Number:"))
        self.label_5.setText(_translate("MainWindow", "Address:"))
        self.label_6.setText(_translate("MainWindow", "Gender:"))
        self.label_7.setText(_translate("MainWindow", "Education:"))
        self.lineEdit_4.setInputMask(_translate("MainWindow", "+62 000 0000 000"))
        self.lineEdit_4.setText(_translate("MainWindow", "+62   "))
        self.comboBox.setItemText(1, _translate("MainWindow", "Male"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Female"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "Elementary School"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "Junior High School"))
        self.comboBox_2.setItemText(3, _translate("MainWindow", "Senior High School"))
        self.comboBox_2.setItemText(4, _translate("MainWindow", "Diploma"))
        self.comboBox_2.setItemText(5, _translate("MainWindow", "Bachelor’s Degree"))
        self.comboBox_2.setItemText(6, _translate("MainWindow", "Master’s Degree"))
        self.comboBox_2.setItemText(7, _translate("MainWindow", "Doctoral Degree"))
        self.pushButton.setText(_translate("MainWindow", "Save"))
        self.pushButton_2.setText(_translate("MainWindow", "Clear"))
        self.label_8.setText(_translate("MainWindow", "Created By : Fernandao Kwangtama Tekayadi (F1D022120)"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
